### ISSUE TITLE
assert(TOLERANCE_NONZERO) thrown

### ISSUE THREAD

**Issue by MauriceGit** [hajimehoshi/go-libtess2#1]
Hello,

first of all - Thanks a lot for this library, it's fast, convenient and easy to use!

I stumbled upon an issue today. The assertion (assert(TOLERANCE_NONZERO)) is thrown in sweep.go:859.
It seems like TOLERANCE_NONZERO is set to false and not altered. Is that correct?

The original call to Tesselate was: 
lt2.Tesselate([]lt2.Contour{vertices}, lt2.WindingRuleOdd)

with vertices: 
{458.14813 845.1371 0} 
{458.63016 845.09753 0} 
{458.63016 845.2361 0} 
{458.7299 845.2361 0} 
{458.7299 844.95935 0} 
{458.63016 844.95935 0} 
{458.63016 844.78156 0} 
{458.13147 844.82074 0} 
{458.14813 845.1371 0}

There is no assertion, if I just set TOLERANCE_NONZERO to true. But I'm not sure, if that is still correct generally...

Thanks,
best regards,
Maurice

**Comment by hajimehoshi** [comment]
Hi,

Thank you for reporting!

Unfortunately, I don't maintain this repository and I'm not sure what the code does since I have just ported this from C version. I tried to understand what it does but I don't have enough bandwidth.

Then I'm also not sure we should enable `TOLERANCE_NONZERO` or not. If it seems fine to enable this, I'm OK to accept a PR.

**Comment by MauriceGit** [comment]
Hi,

no worries, I understand that and appreciate the fast response!
When I find some time, I will try the failing polygons and see, if we can set the flag to true kind-of safely. If so, I'll create a pull-request.

**Comment by MauriceGit** [comment]
Merged to master, Thx!
